### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by evildoerX** [kuaifan/weiui#16]
系统：macOS 10.14.5

执行命令：weiui xxx

报错：
```
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/usr/local/lib/node_modules/weiui-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/weiui-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/weiui-cli/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

**Comment by kuaifan** [comment]
试试看重装weiui-cli
```sh
sudo npm install weiui-cli -g
```

**Comment by kuaifan** [comment]
安装nodejs稳定版就可以
